### ISSUE TITLE
Error viewing blog post: Call to a member function diffForHumans() on string

### ISSUE THREAD

**Issue by connecteev** [binshops/laravel-blog#101]
Clicking to view a blog post shows Error: Call to a member function diffForHumans() on string

**Steps:**

1. Install https://github.com/binshops/laravel-blog/ on my Mac (running PHP 8.2.3, using Laravel 10.11.0)
2. Go to http://127.0.0.1:8000/blog_admin to complete setup
3. Create a new blog post
4. After publishing the blog post, click "View blog post", and you are taken to this page with an error: 
5. http://127.0.0.1:8000/en/blog/community-wisdom-explaining-strategy-to-your-team-making-the-most-of-11s-with-skip-manager-dealing-

Error: Call to a member function diffForHumans() on string
See the attached screenshot.
<img width="948" alt="image" src="https://github.com/binshops/laravel-blog/assets/64816/bee00e42-e773-4f17-87aa-3835605646e3">

**Comment by samberrry** [comment]
fixed, 
new version v8.1.8.
