### ISSUE TITLE
Fulltext Search - search throughout all blog posts

### ISSUE THREAD

**Issue by medab123** [binshops/laravel-blog#109]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_fulltext' doesn't exist (Connection: mysql, SQL: select * from `laravel_fulltext` where MATCH (indexed_title, indexed_content) AGAINST (+f* IN BOOLEAN MODE) order by (1.5 * (MATCH (indexed_title) AGAINST (f*)) + 1 * (MATCH (indexed_title, indexed_content) AGAINST (f*)) ) DESC limit 100)

**Comment by samberrry** [comment]
make sure you have run the migrations.
