### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jim1506** [binshops/laravel-blog#28]
I installed this with a basic Laravel 7 setup. Ran the ui and your composer and then migrate etc. I also amended the User.php as instructed and ran the migration.

I amended your config file to set User to \App\User.

Logged in on my local machine by registering and of course I got to the "your are logged in".

However when I then tried to run http://localhost:8000/blog_admin/setup I received a 401 unauthorized message,

**Comment by sam-beri** [comment]
Hi dear @jim1506 
have you changed the User model?
set to return true and check it again.

**Comment by SvetoslavStefanov** [comment]
I'm having the same issue. Fresh installation, changed everything as described in the Installation page (User model as well, it's returning true by default), but still getting 401.
Do I have to add something in routes/web.php?

**Comment by sam-beri** [comment]
@SvetoslavStefanov Hi, which Laravel version are you using?
No there is no need to change anything in routes/web.php.

**Comment by SvetoslavStefanov** [comment]
> @SvetoslavStefanov Hi, which Laravel version are you using?
> No there is no need to change anything in routes/web.php.

Ops, my bad. This was the most important thing:
Laravel Framework 7.30.4
OS: Windows (with xampp)

Fresh installation.

**Comment by Merite15** [comment]
I have a same blog in fresh laravel 9 installation. When i try to access in /blog_admin/setup i have a 401 error

**Comment by aliraza170** [comment]
I have a same blog in fresh laravel 9 installation. When i try to access in /blog_admin/setup i have a 401 unauthorized error

**Comment by samberrry** [comment]
@aliraza170 try to login first, the setup url is protected.

**Comment by aliraza170** [comment]
> 

I have logged in but still I see this issue, I just installed it on my local host its working here, but when I uploaded on to my ec2 amazon server its showing me 401 on /blog_admin/ and 404 on /en/blog/

**Comment by samberrry** [comment]
may be you did not add `canManageBinshopsBlogPosts`, please make sure you followed the instructions correctly.

**Comment by aliraza170** [comment]
I have already added it

**Comment by aliraza170** [comment]
How can I reinstall it on server ? may be I have already done the setup on local this could be issue ?

**Comment by aliraza170** [comment]
should I need to delete or change anything to reinstall ?

**Comment by aliraza170** [comment]
https://hackers.com.pk
you can register a new user and can test

**Comment by SvetoslavStefanov** [comment]
In your console type ‘php artisan route:list’ to see if blog_admin is there. If it’s not, you probably haven’t install the package on that server. Try running composer install ..package name. Then follow the instructions for vendor push commands and everything.

**Comment by aliraza170** [comment]
> php artisan route:list

GET|HEAD   blog_admin ............. binshopsblog.admin.index › BinshopsBlog\Controllers › BinshopsAdminController@index

I have already this

**Comment by aliraza170** [comment]
Discovering packages.

  binshops/laravel-blog ............................................................................................ DONE
  cviebrock/eloquent-sluggable ..................................................................................... DONE
  intervention/image ............................................................................................... DONE
  laravel/sail ..................................................................................................... DONE
  laravel/sanctum .................................................................................................. DONE
  laravel/tinker ................................................................................................... DONE
  laravel/ui ....................................................................................................... DONE
  nesbot/carbon .................................................................................................... DONE
  nunomaduro/collision ............................................................................................. DONE
  nunomaduro/termwind .............................................................................................. DONE
  spatie/laravel-ignition .......................................................................................... DONE

**Comment by aliraza170** [comment]
canManageBinshopsBlogPosts, changing it to true resolved my issue
