### ISSUE TITLE
Searching not working

### ISSUE THREAD

**Issue by tingan** [binshops/laravel-blog#29]
I install and config the package as document for an existing laravel project, but i get Sorry, but there were no results!
any help for the fulltext search? thanks.

`
 php artisan laravel-fulltext:all 'HessamCMS\Models\HessamPost'

                                                                      
  There are no commands defined in the "laravel-fulltext" namespace. 
`

**Comment by sam-beri** [comment]
Hi Tingan,
there is no need to run any command for fulltext search. I checked it works on a fresh laravel.
