### ISSUE TITLE
Trying to get property 'category' of non-object

### ISSUE THREAD

**Issue by tingan** [binshops/laravel-blog#30]
Hi,
I added second language(Chinese(Mandarin) for laravel blog, then add a category under the second language. Then save category, i got Trying to get property 'category' of non-object. The categories only show english categories. Can be a bug, thx.

`
Trying to get property 'category_name' of non-object (View: vendor/hessam/laravel-blogger/src/Views/hessamcms_admin/categories/_category_partial.blade.php)
`

The bug only happen when create category under non-english language.

**Comment by sam-beri** [comment]
Hi,
fixed in the latest version of package: v9.2.1.
