### ISSUE TITLE
routes

### ISSUE THREAD

**Issue by jahstation** [binshops/laravel-blog#33]
maybe is not an issue, but ive not any route of the blog, just auth, after a fresh installation on laravel 8.

**Comment by sam-beri** [comment]
on a fresh install auth package:
```
composer require laravel/ui
php artisan ui vue --auth

```
then you have auth routes. Then be sure you are logged in and you should setup your package: _**/blog_admin/setup**_
than:
Admin panel URI: /blog_admin Front URI: /en/blog
