### ISSUE TITLE
post detail not show the style as created

### ISSUE THREAD

**Issue by kiwango** [binshops/laravel-blog#34]
Thanks much for package, I was create a post with different style like h1, h2, bold italic etc as ckeeditor provided but once published no style shown in output/front end and when go back to the backend editor the style change itself no style existing. Please find the image attached. will you please provide the code which will help to solve the problem
![blog](https://user-images.githubusercontent.com/46191803/112748654-d3392900-8fc5-11eb-963b-09bfe3053954.JPG)

**Comment by sam-beri** [comment]
Hello @kiwango,
please give us the code and style you put in the ckeditor. 
Thanks

**Comment by kiwango** [comment]
Thanks for quick reply, here is image which show the view of post body in editor while in frontview nothing then after save the post when back to edit the style does not exist find image.
![edit](https://user-images.githubusercontent.com/46191803/112759861-96892400-8ffd-11eb-8cd2-9adaec3a346c.JPG)
This look like the edito does not work or what ![no-style](https://user-images.githubusercontent.com/46191803/112759907-c9cbb300-8ffd-11eb-860d-d4f877357ce1.JPG)

**Comment by kiwango** [comment]
It seems like the HTML Tags not saved in database
![blogpost3](https://user-images.githubusercontent.com/46191803/116812069-5d405880-ab55-11eb-8c2a-8676f675de97.JPG)

**Comment by kiwango** [comment]
> Hello @kiwango,
> please give us the code and style you put in the ckeditor.
> Thanks

Hi, Any solution concern the style please

**Comment by samberrry** [comment]
I close this issue as I could not generate that.
