### ISSUE TITLE
Error in sluggable function

### ISSUE THREAD

**Issue by smart0120** [binshops/laravel-blog#43]
I tried to add laravel-blog into my laravel project

Laravel version  8.49.0
laravel-blog version: 8.1.2

but I got this error
**Declaration of BinshopsBlog\Models\BinshopsBlogPost::sluggable() must be compatible with Cviebrock\EloquentSluggable\Sluggable::sluggable(): array**

I found solution [here](https://laracasts.com/discuss/channels/general-discussion/symfonycomponenterrorhandlererrorfatalerror-declaration-of-appproductsluggable-must-be-compatible-with-cviebrockeloquentsluggablesluggablesluggable-array)

I think the solution is to change `vendor/binshops/laravel-blog/src/Models/BinshopsBlogPost.php (line 61)`
```
public function sluggable(): array
{
 ... ...
}
```

I used DO app for server

unfortunately, DO app doesn't support editing package files

**Comment by samberrry** [comment]
@smart0120 
thanks for reporting.
We will release your fix soon.
Thanks for your contribution.

**Comment by samberrry** [comment]
@smart0120 
the package updated to v8.1.3 version.

**Comment by smart0120** [comment]
The error is fixed to use v8.1.3
Thanks for you response

**Comment by samberrry** [comment]
Thank you for your fix and reporting.

Have a nice day 

 

From: smart0120 ***@***.***>
Reply-To: binshops/laravel-blog ***@***.***>
Date: Thursday, July 1, 2021 at 7:00 AM
To: binshops/laravel-blog ***@***.***>
Cc: Sam ***@***.***>, State change ***@***.***>
Subject: Re: [binshops/laravel-blog] Error in sluggable function (#43)

 

The error is fixed to use v8.1.3
Thanks for you response

**Comment by jacovdbergh** [comment]
This error is still present in v9.2.1 it seems
