### ISSUE TITLE
Bangali language category and post not inserting 

### ISSUE THREAD

**Issue by Anowar98** [binshops/laravel-blog#44]
If I am trying to add new category or post in bangali language then it's not inserting in database  and also not showing in fontend.

**Comment by samberrry** [comment]
![Screen Shot 2021-10-18 at 4 51 36 PM](https://user-images.githubusercontent.com/20775532/137811790-96c17c6d-b73c-40d1-a2f8-49b141a47776.png)
As you see I've added bangali language, and also a sample post for bangali language. It seems that there is no issue. 
Thanks
