### ISSUE TITLE
Database seeder uses MySQL injection 

### ISSUE THREAD

**Issue by hozmaster** [binshops/laravel-blog#59]
CreateLaravelFulltextTable-class contains direct DB::Connection injection which creates columns for text search which uses however MySQL specific column type. Of course this works only when used DB engine is actually MySQL and perhaps MariaSQL.

However, before knew of this, I l already selected Postgresql  so did have to commented out two lines that specific class before it went trough.

And you should suggest npm commands anyway since if took code via composer it does not contains predefined web files.

**Comment by samberrry** [comment]
Hi, 
yes. Actually we are using a clone of this package: https://github.com/swisnl/laravel-fulltext 
the fulltext logic is coming from that package with some minor changes. As you know laravel does not support fulltext, postgres too. 
I think I would be better to be commented for postgres installations ;)

**Comment by hozmaster** [comment]
Ok, thank you for your reply. What you think, is search able to implement using Laravel Scout ? https://laravel.com/docs/8.x ?/scout

**Comment by samberrry** [comment]
welcome ;)
yes it's possible. But needs some development. The search mechanism should be changed.
