### ISSUE TITLE
404 After updating blog prefix.

### ISSUE THREAD

**Issue by usman-xs4arabia-dev** [binshops/laravel-blog#68]
When I try to update the blog prefix in config file then after updating I'm getting 404 against some urls like add blog post etc.

**Comment by samberrry** [comment]
@usman-xs4arabia-dev Hi,
how did you update the prefix? 
prefix sample and url sample
thanks

**Comment by usman-xs4arabia-dev** [comment]
I update the blog_prefix on line 17 in binshopsblog.php file as mentioned bellow:
'blog_prefix' => "blog" (old prefix)
'blog_prefix' => "success_stories" (new prefix)

**Comment by usman-xs4arabia-dev** [comment]
> @usman-xs4arabia-dev Hi, how did you update the prefix? prefix sample and url sample thanks

I update the blog_prefix on line 17 in binshopsblog.php file as mentioned bellow:
'blog_prefix' => "blog" (old prefix)
'blog_prefix' => "success_stories" (new prefix)

**Comment by samberrry** [comment]
> > @usman-xs4arabia-dev Hi, how did you update the prefix? prefix sample and url sample thanks
> 
> I update the blog_prefix on line 17 in binshopsblog.php file as mentioned bellow: 'blog_prefix' => "blog" (old prefix) 'blog_prefix' => "success_stories" (new prefix)
> 
> http://neworeem.trial.com/en/blog (old_url) http://neworeem.trial.com/en/latest_news (new url) (getting 404 against this also)

you set success_stories, and you are accessing a different url lates_news. 

As I checked blog prefix works very well.
'blog_prefix' => "success_stories"
http://127.0.0.1:8000/en/success_stories

Something is wrong with your setup, may be custom changes.

**Comment by usman-xs4arabia-dev** [comment]
> > > @usman-xs4arabia-dev Hi, how did you update the prefix? prefix sample and url sample thanks
> > 
> > 
> > I update the blog_prefix on line 17 in binshopsblog.php file as mentioned bellow: 'blog_prefix' => "blog" (old prefix) 'blog_prefix' => "success_stories" (new prefix)
> > http://neworeem.trial.com/en/blog (old_url) http://neworeem.trial.com/en/latest_news (new url) (getting 404 against this also)
> 
> you set success_stories, and you are accessing a different url lates_news.
> 
> As I checked blog prefix works very well. 'blog_prefix' => "success_stories" http://127.0.0.1:8000/en/success_stories
> 
> Something is wrong with your setup, may be custom changes.

Sorry it was a typo:

I update the blog_prefix on line 17 in binshopsblog.php file as mentioned bellow:
'blog_prefix' => "blog" (old prefix)
'blog_prefix' => "success_stories" (new prefix)

http://neworeem.trial.com/en/blog (old_url)
http://neworeem.trial.com/en/success_stories (new url) (getting 404 against this also)

**Comment by samberrry** [comment]
> 

I checked it with your prefix. Everything is fine. I think there is some custom change with your setup. 
thanks
