### ISSUE TITLE
Laravel 9 composer file issue

### ISSUE THREAD

**Issue by JustAnotherFalseProphet** [binshops/laravel-blog#73]
Hello, thank you for this great package. I am having a problem with the installation.
the command: composer require binshops/laravel-blog
generates an error because I am using a later version of eloquent-sluggable.
my composer file contains "cviebrock/eloquent-sluggable": "^9.0",
Your composer file restricts the latest version to 8: "cviebrock/eloquent-sluggable": "~8.0|~7.0|~6.0|~4.8|~4.7|~4.6|~4.5",
Please updade this so that I can automate the deployment

Kind thanks
Dale

**Comment by dappstatus** [comment]
Same issue here with laravel 9. Fix would be great, so it can be used with the latest Laravel version.

**Comment by samberrry** [comment]
Hi, thanks for reporting.

I will take it into consideration for future developments.

However, if you or anyone else is willing to implement this feature/fix as a pull request, I will be happy to help by ensuring that it is appropriate and coherent with the rest of the project. Thanks.

**Comment by samberrry** [comment]
Hi @dappstatus @JustAnotherFalseProphet , thanks for reporting.

I will take it into consideration for future developments.

However, if you or anyone else is willing to implement this feature/fix as a pull request, I will be happy to help by ensuring that it is appropriate and coherent with the rest of the project. Thanks.

**Comment by JustAnotherFalseProphet** [comment]
Done - it was pretty simple, pull request is in. I'm not sure why you have laravelium/feed in the composer (or what it does for that matter), I can't find it used anywhere and the program works fine without it.

**Comment by samberrry** [comment]
@JustAnotherFalseProphet 

Your PR https://github.com/binshops/laravel-blog/pull/75 has been merged, and new version released -> v9.2.8. 

Thanks for your contribution.

**Comment by samberrry** [comment]
I've also removed the Laravelium/feed package, as it was archived and we could not use it. 
-> release new version v9.2.9

I think this package would be a good replacement:
https://github.com/spatie/laravel-feed
