### ISSUE TITLE
ErrorException PHP 8.0.24 9.33.0 Undefined variable $slot

### ISSUE THREAD

**Issue by Phil-Reck** [binshops/laravel-blog#83]
This happens after adding a new post as an admin, trying to view the post created, the {{ $slot }} variable is undefuned ...
<img width="1465" alt="Screenshot 2022-10-16 at 02 16 32" src="https://user-images.githubusercontent.com/60153430/196010970-31885c79-bc3a-4ffa-9762-739eebe80bda.png">

**Comment by samberrry** [comment]
$slot is your custom variable. please check your edits.
