### ISSUE TITLE
Undefined variable $noLocaleRoute

### ISSUE THREAD

**Issue by thenasty1337** [binshops/laravel-blog#88]
Undefined variable $noLocaleRoute

resources\views\vendor\binshopsblog\index.blade
.php : 64

```
<ul class="binshops-cat-hierarchy">

                    @if($categories)

                        @include("binshopsblog::partials._category_partial", [

    'category_tree' => $categories,

    'name_chain' => $nameChain = "",

    'noLocaleRoute' => $noLocaleRoute

    ])

                    @else

                        <span>No Categories</span>

                    @endif

                </ul>
```

**Comment by samberrry** [comment]
what is your configuration?
single lang? multi lang?

**Comment by yagodecastro** [comment]
I am also having the same problem. My setup is multi lang

**Comment by yagodecastro** [comment]
Minha solução provisória foi agregar `'noLocaleRoute' => null` aos dados de cada view retornada em BinshopsReaderController. Ex:

`return view("binshopsblog::index", [
'lang_list' => BinshopsLanguage::all('locale', 'name'),
            'locale' => $request->get("locale"),
            'lang_id' => $request->get('lang_id'),
            'category_chain' => $categoryChain,
            'categories' => $rootList,
            'posts' => $posts,
            'title' => $title,
            **'noLocaleRoute' => null**
        ]);`
