### ISSUE TITLE
Attempt to read property "locale" on null

### ISSUE THREAD

**Issue by rabol** [binshops/laravel-blog#89]
Hi

just did a new Laravel app

Laravel new blog
composer require laravel/breeze --dev
php artisan breeze:install

and then the steps in the readme

when I access the url: http://blog.test/blog_admin/ i get the error
the error comes from LoadLanguage.php when it try the set the language the first time

quick fix was like this:

```
        $request->attributes->add([
            'locale' => $lang->locale ?? 'en',
            'language_id' => $lang->id ?? 0
        ]);
```

**Comment by samberrry** [comment]
@rabol  did you also call `/blog_admin/setup`, I think you missed this step.

**Comment by rabol** [comment]
I did not, that would solve the issue - thanks

**Comment by samberrry** [comment]
welcome. I close the issue. 
have a great day.
