### ISSUE TITLE
Unauthorized on binshops/laravel-blog urls

### ISSUE THREAD

**Issue by alanretubis** [binshops/laravel-blog#91]
Hi, I've install the package in **Laravel 9 and Ubuntu 20.04**. When is go to /blog_admin/setup/ is gives me an "**Unauthorized**" message.
This is a fresh Laravel installation. I'm just wondering is Laravel 9 is already supported?

I hope someone can help me. Thanks a lot.

**Comment by samberrry** [comment]
Hi,
yes it supports. 
You must be logged in as admin user then call `blog_admin/setup`. 

have a great day.
