### ISSUE TITLE
binshopsblog : blog_admin is returning 401 Unauthorized 

### ISSUE THREAD

**Issue by aliraza170** [binshops/laravel-blog#99]
I have installed blog_admin on my cc2 amazon and installed all the packages followed by the documentation but still I am facing 401 error on admin and 404 error on frontend side of this application. 

https://hackers.com.pk/blog_admin/

**Comment by samberrry** [comment]
Hi,
please make sure that you have logged in with the user which has the appropriate permission to open /blog_admin and the user satisfies your `canManageBinshopsBlogPosts` method (step 5). Take attention this boilerplate method returns `false` by default it you have just did a copy and paste.

**Comment by aliraza170** [comment]
Yes it solved my issue Thanks,
